// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTokenToUser = `-- name: AssignTokenToUser :exec
UPDATE users SET session_token = $1 WHERE id = $2
`

type AssignTokenToUserParams struct {
	SessionToken pgtype.Text
	ID           pgtype.UUID
}

func (q *Queries) AssignTokenToUser(ctx context.Context, arg AssignTokenToUserParams) error {
	_, err := q.db.Exec(ctx, assignTokenToUser, arg.SessionToken, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, username, hashed_password, created_at, updated_at) VALUES (
				UUIDV7(),
				$1,
				$2,
				NOW(),
				NOW()
)
RETURNING id, username, hashed_password, created_at, updated_at, session_token
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionToken,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllUsers)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password, created_at, updated_at, session_token FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionToken,
	)
	return i, err
}
